import createClient from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript

export const tba = createClient<paths>({
    baseUrl: "https://www.thebluealliance.com/api/v3/",
    headers: {
        "X-TBA-Auth-Key": process.env.TBA_KEY
    }
});